[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.88.0"
default-run = "app"

[features]
default = []
updater = ["dep:tauri-plugin-updater"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "app"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2.3.0", features = [] }

[dependencies]
serde_json = "1.0"
url = "2.5"
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "rustls-tls"] }
serde_yaml = "0.9"
regex = "1.12"
keyring = { version = "3.6", features = ["windows-native", "apple-native"] }
rusqlite = { version = "0.32", features = ["bundled"] }
dirs = "6.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
rust_xlsxwriter = "0.92"
futures-util = "0.3"
tauri = { version = "2.6.2", features = ["tray-icon"] }
tauri-plugin-log = "2"
tauri-plugin-updater = { version = "2.10.1", optional = true }
